apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  gateway-secret: {{ .Values.auth.gatewaySecret | quote }}
